# prompts
GET http://localhost:3333/prompts

###
POST http://localhost:3333/video
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="HeJ-obrigado.mp3"
Content-Type: audio/mpeg

< ./HeJ-obrigado.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
POST http://localhost:3333/video/3cbce8f0-8a20-483f-bdab-52b867ad2434/transcription
Content-Type: application/json

{
  "prompt": "cientistas, descobertas, vírus",
  "videoId": "3cbce8f0-8a20-483f-bdab-52b867ad2434"
}

###
POST http://localhost:3333/ai/openai
Content-Type: application/json

{
  "temperature": 0.5,
  "videoId":"b33f51cf-e2cf-49d5-ad68-558cd03ceacc",
  "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}